### ISSUE TITLE
set background of topic's image to white

### ISSUE THREAD

**Issue by yusufmsabeh** [JSD-0423/Ayman-Maani-Project1#2]
@AymanQ-A-Maani 
some of topic's images have transparent background so when you change the theme of the website to dark theme the image itself does not appear properly
**before**
  ![before](https://cdn.discordapp.com/attachments/1102958718489989282/1107771953579831427/image.png)
---------

**after**
![after](https://cdn.discordapp.com/attachments/1102958718489989282/1107772179816394843/image.png)

Keep up the good work 😉

**Comment by AymanQ-A-Maani** [comment]
What an eagle eye you have mate. kudus to you. I'll work on fixing it. thank you :D
